default:
  image: docker:git
  services:
    - docker:dind-rootless
  tags:
    - docker-in-docker

variables:
  FF_USE_FASTZIP: 1
  FF_NETWORK_PER_BUILD: 1
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - builder

Image Builder:
  stage: builder
  variables:
    GIT_DEPTH: 1
  script:
    - ./ci-builder
  artifacts:
    name: "build-artifacts-${CI_PROJECT_NAME}"
    paths:
      - .artifacts
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG =~ /trigger/
