include:
  - project: ci/hub
    ref:     v1.x
    file:    dind.yaml

workflow:
  rules:
    - if: $BUILD_ME

stages:
  - docker-shell

Image Builder:
  stage: docker-shell
  image: ${DPROXY}docker:git
  variables:
    GIT_DEPTH: 1
  script:
    - ./ci-builder
  artifacts:
    name: "build-artifacts-${CI_PROJECT_NAME}"
    paths:
      - .artifacts
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG =~ /trigger/
