FROM alpine:3 AS mold
RUN apk --no-cache -U upgrade
RUN apk --no-cache add bash coreutils findutils tar docker-cli docker-cli-buildx jq yq wget curl git sed gawk diffutils grep
COPY --chmod=755 entrypoint.sh /.entrypoint/docker-shell
COPY --chmod=755 tools/ /usr/local/bin/
FROM scratch
COPY --from=mold / /
ENTRYPOINT ["/.entrypoint/docker-shell"]
CMD ["bash"]
